version: 2

project_name: trix

before:
  hooks:
    - go mod tidy

builds:
  - id: trix
    binary: trix
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

dockers:
  - image_templates:
      - "ghcr.io/trixsec-dev/trix:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goarch: amd64

  - image_templates:
      - "ghcr.io/trixsec-dev/trix:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/trixsec-dev/trix:{{ .Version }}"
    image_templates:
      - "ghcr.io/trixsec-dev/trix:{{ .Version }}-amd64"
      - "ghcr.io/trixsec-dev/trix:{{ .Version }}-arm64"

  - name_template: "ghcr.io/trixsec-dev/trix:latest"
    image_templates:
      - "ghcr.io/trixsec-dev/trix:{{ .Version }}-amd64"
      - "ghcr.io/trixsec-dev/trix:{{ .Version }}-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Other
      order: 999

release:
  github:
    owner: trixsec-dev
    name: trix
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Tag }}"
