version: 2

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: trix

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: trixsec-dev
    name: trix
  draft: false
  prerelease: auto

dockers:
  - image_templates:
      - "ghcr.io/trixsec-dev/trix:{{ .Tag }}"
      - "ghcr.io/trixsec-dev/trix:latest"
    dockerfile: Dockerfile.goreleaser
