{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trix.fullname" . }}
  labels:
    {{- include "trix.labels" . | nindent 4 }}
rules:
  # Trivy Operator CRDs
  - apiGroups: ["aquasecurity.github.io"]
    resources:
      - vulnerabilityreports
      - clustervulnerabilityreports
      - configauditreports
      - clusterconfigauditreports
      - rbacassessmentreports
      - clusterrbacassessmentreports
      - infraassessmentreports
      - clusterinfraassessmentreports
      - exposedsecretreports
      - sbomreports
      - clustersbomreports
      - clustercompliancereports
    verbs: ["get", "list", "watch"]
  # Core resources for exposure analysis
  - apiGroups: [""]
    resources: ["services", "pods", "namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways", "httproutes", "grpcroutes", "tcproutes", "udproutes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trix.fullname" . }}
  labels:
    {{- include "trix.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "trix.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "trix.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
